// app/privacy/page.jsx


import React from 'react';
import styles from './PrivacyPolicy.module.css';

export const metadata = {
  title: 'Privacy Policy | Photo Studio App',
  description:
    'How Photo Studio App collects, uses, and protects personal data for businesses and their clients.',
};

export default function PrivacyPage() {
  return (
    <main className={styles.wrap}>
      <header className={styles.header}>
        <h1>Photo Studio App Privacy Notice</h1>
        <p className={styles.updated}>Last Updated: September 5, 2025</p>
      </header>

      <section className={styles.intro}>
        <p>
          This Privacy Notice (the <strong>“Notice”</strong>) explains how Photo Studio App, LLC and
          its affiliates (<strong>“Photo Studio App,” “we,” “us,”</strong> or <strong>“our”</strong>)
          collect, use, disclose, and otherwise process personal data in connection with our
          software-as-a-service platform, related websites, and services (collectively, the
          <strong>“Services”</strong>).
        </p>
        <p>
          We process personal data both as a <em>controller</em> (for our own business operations)
          and, frequently, as a <em>processor</em> on behalf of our business customers (e.g.,
          photographers and studios) who use the Services to manage their clients, sessions, orders
          and communications. When we act as a processor, our customer’s privacy policy governs and
          you should contact that business directly to exercise your rights about data they control.
        </p>
      </section>

      <nav className={styles.toc} aria-label="Table of contents">
        <ol>
          <li><a href="#personal-data">Personal Data We Process</a></li>
          <li><a href="#how-we-process">How We Process Personal Data</a></li>
          <li><a href="#disclosures">How We Disclose Personal Data</a></li>
          <li><a href="#transfers">International Data Transfers</a></li>
          <li><a href="#security">How We Secure Personal Data</a></li>
          <li><a href="#retention">How Long We Retain Personal Data</a></li>
          <li><a href="#rights">Your Rights and Choices</a></li>
          <li><a href="#cookies">Cookies & Tracking Technologies</a></li>
          <li><a href="#children">Children</a></li>
          <li><a href="#automation">Automated Decision-Making</a></li>
          <li><a href="#contact">How to Contact Us</a></li>
          <li><a href="#changes">Changes to This Notice</a></li>
        </ol>
      </nav>

      <section id="personal-data" className={styles.section}>
        <h2>Personal Data We Process</h2>
        <p>
          The personal data we collect depends on who you are and how you interact with the
          Services. We may collect the categories below (examples are illustrative and not
          exhaustive):
        </p>
        <ul>
          <li>
            <strong>Contact Information.</strong> Name, business name, email address, phone number,
            postal address; account credentials (e.g., password) and profile details.
          </li>
          <li>
            <strong>Customer Account Data.</strong> Billing contact(s), subscription details,
            purchase history, studio settings, users and roles, onboarding, and verification data
            (e.g., KYC/identity checks if required for messaging features).
          </li>
          <li>
            <strong>Client & Session Content.</strong> Images and galleries, order details, booking
            information, contracts and signed releases, communication history, and other content
            uploaded to or generated by the Services for your business use.
          </li>
          <li>
            <strong>Payment Information.</strong> Tokenized payment method details and billing
            address processed by our payment processor(s) (e.g., Stripe). We receive limited
            billing details from processors to reconcile accounts; we do not store full card
            numbers.
          </li>
          <li>
            <strong>Communications Usage Data.</strong> Message/call metadata when you send SMS,
            email, or voice via integrated providers (e.g., time/date, sender/recipient, delivery
            status, IP addresses). We do not access message content unless necessary to provide
            support or comply with law.
          </li>
          <li>
            <strong>Device & Online Activity.</strong> IP address, device/browser type, operating
            system, general location (city/region), referring pages, pages viewed, and interactions
            collected via cookies, pixels, and similar technologies on our sites and app.
          </li>
          <li>
            <strong>Professional Information.</strong> Company, role/title, and related business
            details you provide to us.
          </li>
          <li>
            <strong>Support & Feedback.</strong> Information you provide in tickets, chats, calls,
            surveys, or reviews (which may be recorded, where permitted by law).
          </li>
          <li>
            <strong>Public/Third-Party Sources.</strong> We may receive business contact details or
            enrichment from providers (e.g., LinkedIn, data partners) consistent with your
            settings and applicable law.
          </li>
        </ul>
      </section>

      <section id="how-we-process" className={styles.section}>
        <h2>How We Process Personal Data</h2>
        <p>
          We use personal data where necessary to provide and improve the Services and operate our
          business, including:
        </p>
        <ul>
          <li>Creating and managing accounts; authenticating users; providing onboarding.</li>
          <li>Providing, maintaining, and improving features; troubleshooting and support.</li>
          <li>Processing orders and payments; billing and accounting; tax and audit compliance.</li>
          <li>
            Enabling communications (SMS, email, voice) and related routing/metadata processing via
            integrated providers.
          </li>
          <li>Detecting, preventing, and investigating spam, fraud, abuse, and security incidents.</li>
          <li>Complying with legal obligations and enforcing terms and policies.</li>
          <li>
            Sending service-related notices and, where permitted, marketing communications in line
            with your preferences.
          </li>
          <li>
            Analyzing use of the Services, improving user experience, and developing new products.
          </li>
          <li>
            Conducting surveys, webinars, events, and providing resources (e.g., whitepapers).
          </li>
          <li>
            Aggregating, de-identifying, or anonymizing data to generate insights and improve the
            Services. We do not attempt to re-identify data once de-identified.
          </li>
        </ul>
        <p>
          Where required, we rely on your consent (e.g., certain marketing/cookie uses). Otherwise,
          we process data to perform our contract with you, to comply with law, and/or based on our
          legitimate interests such as securing and improving the Services.
        </p>
      </section>

      <section id="disclosures" className={styles.section}>
        <h2>How We Disclose Personal Data</h2>
        <p>We disclose personal data in the following circumstances:</p>
        <ul>
          <li>
            <strong>Service Providers & Subprocessors.</strong> Vendors who help us deliver the
            Services (e.g., hosting and storage, communications, analytics, support, payment
            processing). Examples include Amazon Web Services (hosting/storage), Stripe (payments),
            Twilio/SendGrid or AWS SES (communications), and similar providers. They may access
            personal data only to perform services for us and must protect it appropriately.
          </li>
          <li>
            <strong>Communications & Telecom Partners.</strong> Where you enable messaging or voice,
            routing may involve telecom carriers, aggregators, or over-the-top providers to deliver
            communications. Metadata necessary to transmit messages/calls is shared with those
            providers per their policies and applicable law.
          </li>
          <li>
            <strong>Business Customers.</strong> If you interact with a studio using our platform,
            we share your data with that business as needed to provide the Services to them.
          </li>
          <li>
            <strong>Legal, Safety, and Compliance.</strong> To comply with law or legal process; to
            protect rights, safety, and security; to prevent fraud/abuse; or in emergencies.
          </li>
          <li>
            <strong>Business Transfers.</strong> In connection with mergers, acquisitions, or
            similar transactions, subject to appropriate protections.
          </li>
          <li>
            <strong>Aggregated/De-identified Data.</strong> We may share insights that do not
            identify individuals.
          </li>
        </ul>
      </section>

      <section id="transfers" className={styles.section}>
        <h2>International Data Transfers</h2>
        <p>
          We may transfer personal data to countries other than your own (including the United
          States) where we or our providers operate. When we do, we use appropriate transfer
          mechanisms and safeguards as required by applicable law (e.g., Standard Contractual
          Clauses and supplemental measures, or other approved mechanisms). If you are in the EEA,
          UK, or Switzerland, you may contact us for more information about these safeguards.
        </p>
      </section>

      <section id="security" className={styles.section}>
        <h2>How We Secure Personal Data</h2>
        <p>
          We employ administrative, technical, and physical measures designed to protect personal
          data, taking into account the nature of the data and the state of the art. Controls
          include encryption in transit, least-privilege access, logging/monitoring, and security
          reviews. No system is perfectly secure; please use strong passwords and keep credentials
          confidential.
        </p>
      </section>

      <section id="retention" className={styles.section}>
        <h2>How Long We Retain Personal Data</h2>
        <p>
          We retain personal data only as long as necessary for the purposes described in this
          Notice (e.g., to provide the Services, meet legal/accounting obligations, resolve
          disputes), then delete or de-identify it in accordance with our retention policies and
          applicable law.
        </p>
      </section>

      <section id="rights" className={styles.section}>
        <h2>Your Rights and Choices</h2>
        <p>
          Depending on your location, you may have rights to access, correct, delete, or port your
          personal data; object to or restrict certain processing; and withdraw consent. You may
          also have the right to opt out of targeted advertising or certain profiling.
        </p>
        <ul>
          <li>
            <strong>Account Controls.</strong> When you are an account holder, you can access and
            update many data points in-app. For other requests, contact us using the details below.
          </li>
          <li>
            <strong>Marketing Preferences.</strong> You can unsubscribe via links in our emails or
            adjust preferences in your account. We may still send you service/transactional
            messages.
          </li>
          <li>
            <strong>California/US State Privacy.</strong> If you are a resident of California or
            other US states with privacy laws, you may have the rights described above. We disclose
            personal data only as described in this Notice. We do not knowingly sell personal data.
            You can exercise opt-out choices related to cookies/ads as described below.
          </li>
          <li>
            <strong>EEA/UK/Swiss Users.</strong> You have GDPR rights as stated above. You may also
            lodge a complaint with your data protection authority.
          </li>
        </ul>
        <p>
          If we process your personal data on behalf of a business customer, we will direct you to
          that business to exercise your rights.
        </p>
      </section>

      <section id="cookies" className={styles.section}>
        <h2>Cookies & Other Tracking Technologies</h2>
        <p>
          We use cookies, pixels, and similar tools on our websites and app to remember settings,
          keep you signed in, analyze usage, and personalize content/ads where permitted. You can
          manage preferences via our cookie banner/manager and your browser settings. Note that
          required cookies are necessary for core functionality and cannot be disabled.
        </p>
        <ul>
          <li>
            <strong>Manage Using Your Browser.</strong> Most browsers let you refuse or delete
            cookies. Doing so may affect site functionality.
          </li>
          <li>
            <strong>Universal Signals.</strong> Where legally required and technically feasible, we
            honor global privacy signals (e.g., GPC) for opt-out preferences.
          </li>
          <li>
            <strong>Advertising Choices.</strong> To learn about interest-based advertising choices,
            visit industry sites such as the DAA or NAI. These tools are provided by third parties.
          </li>
        </ul>
      </section>

      <section id="children" className={styles.section}>
        <h2>Children</h2>
        <p>
          The Services are not directed to children under 18 (or the equivalent minimum age in your
          jurisdiction). We do not knowingly collect personal data from children. If you believe a
          child has provided personal data, contact us and we will take appropriate steps to remove
          it.
        </p>
      </section>

      <section id="automation" className={styles.section}>
        <h2>Automated Decision-Making</h2>
        <p>
          We may use automated systems to help detect spam, fraud, or abuse and to safeguard the
          Services. We do not make decisions with legal or similarly significant effects without
          human involvement where required by law. You may request human review of certain
          automated decisions by contacting us.
        </p>
      </section>

      <section id="contact" className={styles.section}>
        <h2>How to Contact Us</h2>
        <p>
          Questions or concerns about this Notice or our practices? Contact our privacy team at
          <a href="mailto:privacy@photostudioapp.com">privacy@photostudioapp.com</a> or write to:
        </p>
        <address>
          Photo Studio App, LLC<br />
          Attn: Privacy<br />
          198 Abner Ln.<br />
          Montgomery, TX 77356 USA
        </address>
      </section>

      <section id="changes" className={styles.section}>
        <h2>Changes to This Notice</h2>
        <p>
          We may update this Notice from time to time to reflect legal, technical, or business
          developments. The updated version will be posted here with a new “Last Updated” date. If
          we make material changes that affect your rights, we will provide additional notice (e.g.,
          in-app message or email) as required by law.
        </p>
      </section>

      <section className={styles.appendix}>
        <h3>Appendix: Key Subprocessors/Partners (Illustrative)</h3>
        <ul>
          <li>Amazon Web Services (hosting, storage, infrastructure)</li>
          <li>Stripe (payment processing)</li>
          <li>Twilio / SendGrid or AWS SES (communications and email delivery)</li>
          <li>Analytics and error monitoring providers (e.g., first- or third-party tools)</li>
          <li>Customer support and helpdesk tools</li>
        </ul>
        <p className={styles.note}>
          The specific providers we use may change over time. We will maintain an up-to-date list in
          our help center or upon request.
        </p>
      </section>
    </main>
  );
}


